### ISSUE TITLE
Can you share how to get this compiled in windows? thx!

### ISSUE THREAD

**Issue by 2betop** [sass/node-sass-binaries#33]
I tried hours and always got this error, I would appreciate if you give me some direction.

```
Error	8	error LNK2001: unresolved external symbol "class v8::Handle<class v8::Value> __cdecl RenderSync(class v8::Arguments const &)" (?RenderSync@@YA?AV?$Handle@VValue@v8@@@v8@@ABVArguments@2@@Z)	node-sass\build\binding.obj	binding

```

**Comment by 2betop** [comment]
I was using visual studio 2013

**Comment by LaurentGoderre** [comment]
It took me a really long time to figure it out as well. I can't quite remember exactly the step to follow but I can help you get ti working. First, what are the folders in `C:\Users\[YOUR USER]\.node-gyp\0.10.x`?

**Comment by 2betop** [comment]
It's in `C:\Users\[MY USER]\.node-gyp\0.9.11`

**Comment by 2betop** [comment]
Because i need it to work in node >= 0.8.0, so i got to build at least 4 version. 

0.8.0 - 0.9.2:  build with `--target=0.8.0` (share the same v8 version)
0.9.3 - 0.9.6  build with `--target=0.9.3` (share the same v8 version)
0.9.7 - 0.9.10 build with `--target=0.9.7` (share the same v8 version)
0.9.11 - 0.10.x build with `--target=0.9.11` (share the same v8 version)

**Comment by LaurentGoderre** [comment]
ok, what is in that folder?

**Comment by 2betop** [comment]
you mean 
![image](https://cloud.githubusercontent.com/assets/2698393/5922039/6087a058-a683-11e4-8b1d-3746a2dc0a63.png) ?

the folder full path is `C:\Users\2betop\.node-gyp\0.9.11`

**Comment by 2betop** [comment]
should i use a more recently version? 0.10.x ?

**Comment by LaurentGoderre** [comment]
What I have done is renamed the `ia32` folder to `x86` then in Visual Studio I changed the following config

![nodesassvs](https://cloud.githubusercontent.com/assets/1090826/5923248/0a43afba-a620-11e4-887b-ba7d3f3a118c.PNG)

**Comment by 2betop** [comment]
Anything else? because i still get that error.

**Comment by LaurentGoderre** [comment]
Did you get the submodules?

**Comment by 2betop** [comment]
Oh it works after i switch to node 0.10.36, thank you so much

**Comment by LaurentGoderre** [comment]
Np, sorry I don't have any experience building in node lower than 0.10

**Comment by 2betop** [comment]
thx again, you saved me!
